name: Build android version

on:
  workflow_dispatch:

env:
  DIST_TAG: preview

jobs:
  BuildAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      
      - name: Install libs on ubuntu
        run: sudo apt install -y libusb-1.0-0-dev libudev-dev

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      
      - name: Install Dependencies
        run: npm install -g cordova@10 && npm ci

      - name: Build
        run: npx quasar build -m android
        
      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        id: sign_app
        with:
          releaseDirectory: dist/cordova/android/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename file
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} dist/cordova/android/apk/release/Sync2-android-${{github.event.release.tag_name}}}.apk

      - name: Upload released files
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/cordova/android/apk/release/Sync2-android-${{github.event.release.tag_name}}}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}